name: linux-build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Create Build Environment
      env:
        RUNNER_WORKSPACE: ${{ runner.workspace }}
      working-directory: ${{ github.workspace }}
      run: |
        cmake -E make_directory "${RUNNER_WORKSPACE}/build"

    - name: Configure CMake
      working-directory: ${{ runner.workspace }}/build
      run: |
        cmake "${GITHUB_WORKSPACE}" -G Ninja \
          "-DCMAKE_BUILD_TYPE=${BUILD_TYPE}"

    - name: Build
      working-directory: ${{ runner.workspace }}/build
      run: cmake --build . --config "${BUILD_TYPE}"

    #- name: Test
    #  working-directory: ${{ runner.workspace }}/build
    #  run: ctest --build-config "${BUILD_TYPE}" --output-on-failure
